/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScenarioRouteImport } from './routes/scenario'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PicksKrRouteImport } from './routes/picks.kr'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioRoute = ScenarioRouteImport.update({
  id: '/scenario',
  path: '/scenario',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PicksKrRoute = PicksKrRouteImport.update({
  id: '/picks/kr',
  path: '/picks/kr',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analysis': typeof AnalysisRoute
  '/dashboard': typeof DashboardRoute
  '/portfolio': typeof PortfolioRoute
  '/reports': typeof ReportsRoute
  '/scenario': typeof ScenarioRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/picks/kr': typeof PicksKrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analysis': typeof AnalysisRoute
  '/dashboard': typeof DashboardRoute
  '/portfolio': typeof PortfolioRoute
  '/reports': typeof ReportsRoute
  '/scenario': typeof ScenarioRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/picks/kr': typeof PicksKrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analysis': typeof AnalysisRoute
  '/dashboard': typeof DashboardRoute
  '/portfolio': typeof PortfolioRoute
  '/reports': typeof ReportsRoute
  '/scenario': typeof ScenarioRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/picks/kr': typeof PicksKrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analysis'
    | '/dashboard'
    | '/portfolio'
    | '/reports'
    | '/scenario'
    | '/settings'
    | '/watchlist'
    | '/picks/kr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analysis'
    | '/dashboard'
    | '/portfolio'
    | '/reports'
    | '/scenario'
    | '/settings'
    | '/watchlist'
    | '/picks/kr'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analysis'
    | '/dashboard'
    | '/portfolio'
    | '/reports'
    | '/scenario'
    | '/settings'
    | '/watchlist'
    | '/picks/kr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalysisRoute: typeof AnalysisRoute
  DashboardRoute: typeof DashboardRoute
  PortfolioRoute: typeof PortfolioRoute
  ReportsRoute: typeof ReportsRoute
  ScenarioRoute: typeof ScenarioRoute
  SettingsRoute: typeof SettingsRoute
  WatchlistRoute: typeof WatchlistRoute
  PicksKrRoute: typeof PicksKrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario': {
      id: '/scenario'
      path: '/scenario'
      fullPath: '/scenario'
      preLoaderRoute: typeof ScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picks/kr': {
      id: '/picks/kr'
      path: '/picks/kr'
      fullPath: '/picks/kr'
      preLoaderRoute: typeof PicksKrRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalysisRoute: AnalysisRoute,
  DashboardRoute: DashboardRoute,
  PortfolioRoute: PortfolioRoute,
  ReportsRoute: ReportsRoute,
  ScenarioRoute: ScenarioRoute,
  SettingsRoute: SettingsRoute,
  WatchlistRoute: WatchlistRoute,
  PicksKrRoute: PicksKrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
