/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ScenarioRouteImport } from './routes/scenario'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SnapshotsIndexRouteImport } from './routes/snapshots.index'
import { Route as ThemesSlugRouteImport } from './routes/themes.$slug'
import { Route as SnapshotsSnapshotIdRouteImport } from './routes/snapshots.$snapshotId'
import { Route as PicksUsRouteImport } from './routes/picks.us'
import { Route as PicksKrRouteImport } from './routes/picks.kr'
import { Route as AnalysisTickerPullbackRouteImport } from './routes/analysis.$ticker.pullback'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioRoute = ScenarioRouteImport.update({
  id: '/scenario',
  path: '/scenario',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotsIndexRoute = SnapshotsIndexRouteImport.update({
  id: '/snapshots/',
  path: '/snapshots/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesSlugRoute = ThemesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ThemesRoute,
} as any)
const SnapshotsSnapshotIdRoute = SnapshotsSnapshotIdRouteImport.update({
  id: '/snapshots/$snapshotId',
  path: '/snapshots/$snapshotId',
  getParentRoute: () => rootRouteImport,
} as any)
const PicksUsRoute = PicksUsRouteImport.update({
  id: '/picks/us',
  path: '/picks/us',
  getParentRoute: () => rootRouteImport,
} as any)
const PicksKrRoute = PicksKrRouteImport.update({
  id: '/picks/kr',
  path: '/picks/kr',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisTickerPullbackRoute = AnalysisTickerPullbackRouteImport.update({
  id: '/$ticker/pullback',
  path: '/$ticker/pullback',
  getParentRoute: () => AnalysisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/automation': typeof AutomationRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/portfolio': typeof PortfolioRoute
  '/reports': typeof ReportsRoute
  '/scenario': typeof ScenarioRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/themes': typeof ThemesRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/picks/kr': typeof PicksKrRoute
  '/picks/us': typeof PicksUsRoute
  '/snapshots/$snapshotId': typeof SnapshotsSnapshotIdRoute
  '/themes/$slug': typeof ThemesSlugRoute
  '/snapshots/': typeof SnapshotsIndexRoute
  '/analysis/$ticker/pullback': typeof AnalysisTickerPullbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/automation': typeof AutomationRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/portfolio': typeof PortfolioRoute
  '/reports': typeof ReportsRoute
  '/scenario': typeof ScenarioRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/themes': typeof ThemesRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/picks/kr': typeof PicksKrRoute
  '/picks/us': typeof PicksUsRoute
  '/snapshots/$snapshotId': typeof SnapshotsSnapshotIdRoute
  '/themes/$slug': typeof ThemesSlugRoute
  '/snapshots': typeof SnapshotsIndexRoute
  '/analysis/$ticker/pullback': typeof AnalysisTickerPullbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/automation': typeof AutomationRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/portfolio': typeof PortfolioRoute
  '/reports': typeof ReportsRoute
  '/scenario': typeof ScenarioRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/themes': typeof ThemesRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/picks/kr': typeof PicksKrRoute
  '/picks/us': typeof PicksUsRoute
  '/snapshots/$snapshotId': typeof SnapshotsSnapshotIdRoute
  '/themes/$slug': typeof ThemesSlugRoute
  '/snapshots/': typeof SnapshotsIndexRoute
  '/analysis/$ticker/pullback': typeof AnalysisTickerPullbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analysis'
    | '/automation'
    | '/calendar'
    | '/dashboard'
    | '/portfolio'
    | '/reports'
    | '/scenario'
    | '/search'
    | '/settings'
    | '/themes'
    | '/watchlist'
    | '/picks/kr'
    | '/picks/us'
    | '/snapshots/$snapshotId'
    | '/themes/$slug'
    | '/snapshots/'
    | '/analysis/$ticker/pullback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analysis'
    | '/automation'
    | '/calendar'
    | '/dashboard'
    | '/portfolio'
    | '/reports'
    | '/scenario'
    | '/search'
    | '/settings'
    | '/themes'
    | '/watchlist'
    | '/picks/kr'
    | '/picks/us'
    | '/snapshots/$snapshotId'
    | '/themes/$slug'
    | '/snapshots'
    | '/analysis/$ticker/pullback'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analysis'
    | '/automation'
    | '/calendar'
    | '/dashboard'
    | '/portfolio'
    | '/reports'
    | '/scenario'
    | '/search'
    | '/settings'
    | '/themes'
    | '/watchlist'
    | '/picks/kr'
    | '/picks/us'
    | '/snapshots/$snapshotId'
    | '/themes/$slug'
    | '/snapshots/'
    | '/analysis/$ticker/pullback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalysisRoute: typeof AnalysisRouteWithChildren
  AutomationRoute: typeof AutomationRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  PortfolioRoute: typeof PortfolioRoute
  ReportsRoute: typeof ReportsRoute
  ScenarioRoute: typeof ScenarioRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ThemesRoute: typeof ThemesRouteWithChildren
  WatchlistRoute: typeof WatchlistRoute
  PicksKrRoute: typeof PicksKrRoute
  PicksUsRoute: typeof PicksUsRoute
  SnapshotsSnapshotIdRoute: typeof SnapshotsSnapshotIdRoute
  SnapshotsIndexRoute: typeof SnapshotsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario': {
      id: '/scenario'
      path: '/scenario'
      fullPath: '/scenario'
      preLoaderRoute: typeof ScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshots/': {
      id: '/snapshots/'
      path: '/snapshots'
      fullPath: '/snapshots/'
      preLoaderRoute: typeof SnapshotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes/$slug': {
      id: '/themes/$slug'
      path: '/$slug'
      fullPath: '/themes/$slug'
      preLoaderRoute: typeof ThemesSlugRouteImport
      parentRoute: typeof ThemesRoute
    }
    '/snapshots/$snapshotId': {
      id: '/snapshots/$snapshotId'
      path: '/snapshots/$snapshotId'
      fullPath: '/snapshots/$snapshotId'
      preLoaderRoute: typeof SnapshotsSnapshotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picks/us': {
      id: '/picks/us'
      path: '/picks/us'
      fullPath: '/picks/us'
      preLoaderRoute: typeof PicksUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picks/kr': {
      id: '/picks/kr'
      path: '/picks/kr'
      fullPath: '/picks/kr'
      preLoaderRoute: typeof PicksKrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$ticker/pullback': {
      id: '/analysis/$ticker/pullback'
      path: '/$ticker/pullback'
      fullPath: '/analysis/$ticker/pullback'
      preLoaderRoute: typeof AnalysisTickerPullbackRouteImport
      parentRoute: typeof AnalysisRoute
    }
  }
}

interface AnalysisRouteChildren {
  AnalysisTickerPullbackRoute: typeof AnalysisTickerPullbackRoute
}

const AnalysisRouteChildren: AnalysisRouteChildren = {
  AnalysisTickerPullbackRoute: AnalysisTickerPullbackRoute,
}

const AnalysisRouteWithChildren = AnalysisRoute._addFileChildren(
  AnalysisRouteChildren,
)

interface ThemesRouteChildren {
  ThemesSlugRoute: typeof ThemesSlugRoute
}

const ThemesRouteChildren: ThemesRouteChildren = {
  ThemesSlugRoute: ThemesSlugRoute,
}

const ThemesRouteWithChildren =
  ThemesRoute._addFileChildren(ThemesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalysisRoute: AnalysisRouteWithChildren,
  AutomationRoute: AutomationRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  PortfolioRoute: PortfolioRoute,
  ReportsRoute: ReportsRoute,
  ScenarioRoute: ScenarioRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ThemesRoute: ThemesRouteWithChildren,
  WatchlistRoute: WatchlistRoute,
  PicksKrRoute: PicksKrRoute,
  PicksUsRoute: PicksUsRoute,
  SnapshotsSnapshotIdRoute: SnapshotsSnapshotIdRoute,
  SnapshotsIndexRoute: SnapshotsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
